version: '3.8'
services:
  codeigniter3:
    container_name: apache
    build: 
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 7710:80
    networks:
      - sundadigi

  db:
    container_name: mysql
    image: mysql:5.7.44
    # image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3310:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - sundadigi

  phpmyadmin:
    container_name: dbadmin
    image: phpmyadmin/phpmyadmin
    ports:
        - '8082:80'
    restart: always
    environment:
        PMA_HOST: db
    depends_on:
        - db
    networks:
      - sundadigi

volumes:
  db:

networks:
  sundadigi:
    driver: bridge
